name: Build and test
on: [push, workflow_dispatch]

env:
  EM_CACHE_FOLDER: 'emsdk-cache'
  # EM_VERSION: '3.1.60'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - uses: mymindstorm/setup-emsdk@v14
        with:
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      # - name: Set up Cache for build folders
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       build
      #       build-native
      #     key: build-cache-${{ github.sha }}
      #     restore-keys: |
      #       build-cache-
      # - name: Prepare emscripten
      #   run: node ./scripts/install-emscripten.mjs
      # - name: Prepare dependencies
      #   run: |
      #     pnpm install
      - name: Run build wasm
        shell: bash
        run: |
          export EMSCRIPTEN_ROOT="$EMSDK"
          npm run build:js
        env:
          CC: clang
          CXX: clang++
      - name: Run test wasm (Wasm)
        run: |
          npx playwright install-deps
          npx playwright install
          npm run test:js
        env:
          TEST_WEBKIT: 1
      - name: Run build & tests (C++)
        run: |
          npm run build:native
          npm run test:native
        env:
          CC: clang
          CXX: clang++

